---
permalink: rhel-install/reference-system-requirements-for-oncommand-workflow-automation-linux.html 
sidebar: sidebar 
keywords: oncommand workflow automation, system, requirements, install, hardware, requirements, install, wfa 
summary: 'Você deve estar ciente dos requisitos de hardware e software do OnCommand Workflow Automation (WFA) antes de instalar O WFA.' 
---
= Requisitos de sistema para a instalação do OnCommand Workflow Automation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve estar ciente dos requisitos de hardware e software do OnCommand Workflow Automation (WFA) antes de instalar O WFA.



== Requisitos de hardware para a instalação DO WFA

A tabela a seguir lista os requisitos mínimos de hardware e as especificações de hardware recomendadas para o servidor WFA.

[cols="3*"]
|===
| Componente | Requisitos mínimos | Especificações recomendadas 


 a| 
CPU
 a| 
2,27 GHz ou mais rápido, 2 núcleos, 64 bits
 a| 
2,27 GHz ou mais rápido, 2 núcleos, 64 bits



 a| 
RAM
 a| 
4 GB
 a| 
8 GB



 a| 
Espaço livre em disco
 a| 
5 GB
 a| 
20 GB

|===
[NOTE]
====
Se você estiver instalando O WFA em uma máquina virtual (VM), você deve reservar a memória e a CPU necessárias para que a VM tenha recursos suficientes. O instalador não verifica a velocidade da CPU.

====


== Requisitos de software para a instalação DO WFA

A tabela a seguir lista todas as versões do sistema operacional compatíveis com o servidor WFA.

[cols="2*"]
|===
| Sistema operacional | Versão 


 a| 
Red Hat Enterprise Linux
 a| 
6,5, 7,0, sistemas operacionais de 7,1 64 bits, 7,2, 7,3 e 7,4



 a| 
CentOS
 a| 
7,1, 7,2 e 7,3

|===
[NOTE]
====
O WFA deve ser instalado em máquinas físicas dedicadas ou VMs. Você não deve instalar nenhum outro aplicativo no servidor que executa O WFA.

====


== Outro software mínimo necessário

* Um dos seguintes navegadores suportados:
+
** Mozilla Firefox
** Microsoft Internet Explorer
** Google Chrome


* A versão mais recente do Adobe Flash Player para o seu navegador
* Perl v5.10.1
+
Você pode obter informações sobre os módulos Perl que devem ser instalados usando o `./WFA-version_number.bin -l` comando.



Para obter mais detalhes, consulte a ferramenta Matriz de interoperabilidade.

*Informações relacionadas*

http://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^]
