---
permalink: rhel-install/task-restore-regular-the-oncommand-workflow-automation-database-and-configurations-linux.html 
sidebar: sidebar 
keywords: oncommand workflow automation, wfa, cli, restore 
summary: 'Você pode fazer uma restauração regular do banco de dados OnCommand Workflow Automation (WFA) que você fez backup anteriormente usando a interface de linha de comando (CLI). Em uma restauração regular, você só pode restaurar o banco de dados WFA.' 
---
= Restaure (regular) o banco de dados WFA usando a CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode fazer uma restauração regular do banco de dados OnCommand Workflow Automation (WFA) que você fez backup anteriormente usando a interface de linha de comando (CLI). Em uma restauração regular, você só pode restaurar o banco de dados WFA.

.O que você vai precisar
* Você deve ter criado um backup do banco de dados WFA.
* Você precisa ter credenciais de administrador ou arquiteto.


.Passos
. No prompt do shell, navegue para o seguinte diretório no servidor WFA:
+
`WFA_install_location/wfa/bin`

+
`wfa_install_location` É o diretório de instalação DO WFA.

. Restaure o banco de dados DO WFA:
+
`wfa --restore --user=user_name [--password=password] [--location=path]`

+
** _user_name_ é o nome de usuário do usuário admin ou arquiteto.
** _password_ é a senha do usuário.
+
Se não tiver fornecido a palavra-passe, tem de introduzir a palavra-passe quando lhe for pedido.

** _path_ é o caminho completo do diretório para o arquivo de restauração.


. Verifique se a operação de restauração foi bem-sucedida e O WFA está acessível.

