---
permalink: rhel-install/task-back-up-full-the-wfa-database-using-perl-script-linux.html 
sidebar: sidebar 
keywords: oncommand workflow automation, backup, wfa, database, cli 
summary: 'Você pode executar um backup completo do banco de dados do OnCommand Workflow Automation (WFA) usando a interface de linha de comando (CLI) DO WFA. Em um backup completo, o banco de dados WFA, a configuração DO WFA e a chave são copiados.' 
---
= Faça backup (completo) do banco de dados WFA usando a CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode executar um backup completo do banco de dados do OnCommand Workflow Automation (WFA) usando a interface de linha de comando (CLI) DO WFA. Em um backup completo, o banco de dados WFA, a configuração DO WFA e a chave são copiados.

.O que você vai precisar
Você precisa ter credenciais de usuário de administrador ou credenciais de arquiteto.

.Sobre esta tarefa
Em um ambiente de alta disponibilidade, você deve criar backups programados usando APIs REST. Não é possível criar backups usando a CLI quando O WFA estiver no modo failover.

Para obter mais informações, consulte a documentação do REST.

.Passos
. No prompt do shell, navegue para o seguinte diretório no servidor WFA:
+
`WFA_install_location/wfa/bin/.`

+
`WFA_install_location` É o diretório de instalação DO WFA.

. Faça backup do banco de dados DO WFA:
+
`.\wfa --backup --user=USER [--password=PASS] [--location=PATH] [--full]`

+
** _user_ é o nome de usuário do usuário de backup.
** _password_ é a senha do usuário de backup.
+
Se não tiver fornecido a palavra-passe, tem de introduzir a palavra-passe quando lhe for pedido.

** _path_ é o caminho completo do diretório para o arquivo de backup.


. *Opcional:* Verifique se o arquivo de backup foi criado no local especificado.

