---
permalink: windows-install/reference-prerequisites-for-installing-workflow-automation.html 
sidebar: sidebar 
keywords: prerequisites, install, workflow automation 
summary: 'Antes de instalar o OnCommand Workflow Automation (WFA), você deve garantir que você tenha as informações necessárias e que tenha concluído certas tarefas.' 
---
= Pré-requisitos para instalar o Workflow Automation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar o OnCommand Workflow Automation (WFA), você deve garantir que você tenha as informações necessárias e que tenha concluído certas tarefas.

Antes de instalar O WFA em um sistema, você deve ter concluído as seguintes tarefas:

* Transferir o ficheiro de instalação DO WFA a partir do site de suporte da NetApp e copiar o ficheiro para o servidor no qual pretende instalar O WFA
+

NOTE: Você deve ter credenciais válidas para fazer login no site de suporte da NetApp. Se você não tiver credenciais válidas, poderá se Registrar no site de suporte da NetApp para obter as credenciais.

* Verificar se o sistema tem acesso ao seguinte, conforme aplicável:
+
** Controladores de storage
** Gerenciador de data center do Active IQ
** VMware vCenter




[NOTE]
====
Se o seu ambiente requer acessibilidade SSH (Secure Shell), você deve garantir que o SSH esteja habilitado nos controladores de destino.

====
* Verificando se o PowerShell 3,0 ou posterior está instalado
* Garantir que o VMware Power CLI esteja instalado, se você estiver usando O WFA para executar fluxos de trabalho no VMware vSphere
* Recolher as informações de configuração necessárias
* Garantindo que o conetor .Net do MySQL esteja instalado, se você estiver usando o cmdlet Invoke-MysqlQuery




== Informações de configuração necessárias

[cols="3*"]
|===
| Unidade ou sistema | Detalhes | Finalidade 


 a| 
Arrays
 a| 
* Endereço IP
* Nome de utilizador e palavra-passe

 a| 
Realizar operações em sistemas de storage

[NOTE]
====
As credenciais de conta de administrador ou raiz são necessárias para armazenamento (arrays).

====


 a| 
VSphere
 a| 
* Endereço IP
* Nome de usuário e senha de um administrador para vCenter Server

 a| 
Adquirir dados

Realize operações usando APIs VMware


NOTE: Você precisa ter o VMware Power CLI instalado.



 a| 
Repositórios externos, como o OnCommand Balance e bancos de dados personalizados
 a| 
* Endereço IP
* Nome de usuário e senha de uma conta de usuário somente leitura

 a| 
Adquirir dados

Você deve criar o conteúdo WFA relevante, como entradas de dicionário e consultas de cache para os repositórios externos, a fim de adquirir dados dos repositórios externos.



 a| 
Servidor de correio
 a| 
* Endereço IP
* Nome de utilizador e palavra-passe



NOTE: O nome de usuário e a senha são necessários se o servidor de e-mail exigir autenticação.
 a| 
Receba notificações DO WFA por e-mail



 a| 
Servidor AutoSupport
 a| 
* Host de e-mail

 a| 
Enviar mensagens AutoSupport através de SMTP

Se você não tiver um host de e-mail configurado, poderá usar HTTP ou HTTPS para enviar mensagens AutoSupport.



 a| 
Servidor LDAP do Microsoft ative Directory (AD)
 a| 
* Endereço IP
* Nome de utilizador e palavra-passe
* Nome do grupo

 a| 
Autentique e autorize usando AD LDAP ou AD LDAPS



 a| 
Aplicação de gestão SNMP
 a| 
* Endereço IP
* Porta

 a| 
Receber notificações WFA SNMP



 a| 
Servidor syslog
 a| 
* Endereço IP

 a| 
Enviar dados de registo

|===
*Informações relacionadas*

http://mysupport.netapp.com["Suporte à NetApp"^]
