---
permalink: windows-install/task-fully-restore-the-oncommand-workflow-automation-database-using-clis-windows.html 
sidebar: sidebar 
keywords: oncommand workflow automation, restore, wfa, database, cli 
summary: 'Você pode fazer uma restauração completa do banco de dados OnCommand Workflow Automation (WFA) usando a interface de linha de comando (CLI). Em uma restauração completa, você pode restaurar o banco de dados DO WFA, a configuração DO WFA e a chave.' 
---
= Restaurar (completo) banco de dados WFA usando a CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode fazer uma restauração completa do banco de dados OnCommand Workflow Automation (WFA) usando a interface de linha de comando (CLI). Em uma restauração completa, você pode restaurar o banco de dados DO WFA, a configuração DO WFA e a chave.

.O que você vai precisar
* Você deve ter criado um backup do banco de dados WFA.
* Você precisa ter credenciais de administrador ou arquiteto.


.Passos
. No prompt do shell, navegue para o seguinte diretório no servidor WFA:
+
`WFA_install_location\WFA\bin`

+
`wfa_install_location` É o diretório de instalação DO WFA.

. Execute a operação de restauração:
+
`wfa.cmd --restore --full --user=user_name [--password=password] [--location=path] --restart`

+
** _user_name_ é o nome de usuário do usuário admin ou arquiteto.
** _password_ é a senha do usuário.
+
Se não tiver fornecido a palavra-passe, tem de introduzir a palavra-passe quando lhe for pedido.

** _path_ é o caminho completo do diretório para o arquivo de restauração.


. Verifique se a operação de restauração foi bem-sucedida e O WFA está acessível.

