---
permalink: help/task-configure-snmp.html 
sidebar: sidebar 
keywords: configure, SNMP 
summary: 'Você pode configurar o OnCommand Workflow Automation (WFA) para enviar traps SNMP (Simple Network Management Protocol) sobre o status das operações de fluxo de trabalho.' 
---
= Configurar o SNMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar o OnCommand Workflow Automation (WFA) para enviar traps SNMP (Simple Network Management Protocol) sobre o status das operações de fluxo de trabalho.

.Sobre esta tarefa
O arquivo WFA `.mib` fornece informações sobre os traps que são enviados pelo servidor WFA. O `.mib` arquivo está localizado no `<WFA_install_location>\wfa\bin\wfa.mib` diretório no servidor WFA.


NOTE: O servidor WFA envia todas as notificações de trap com um identificador de objeto genérico (1,3.6,1.4,1.789,1.1.12.0).

Você não pode usar strings de comunidade SNMP, `community_string@SNMP_host` como para configuração SNMP.

.Passos
. Faça login NO WFA através de um navegador da Web como usuário admin e, em seguida, acesse o servidor WFA.
. Clique em *Configurações* e, em *Configuração*, clique em *SNMP*.
. Marque a caixa de seleção *Enable SNMP* (Ativar VRF*).
. Insira um endereço IPv4 ou IPv6 ou o nome do host e o número da porta do host de gerenciamento.
+
O WFA envia traps SNMP para o número de porta especificado. O número da porta padrão é 162.

. Na seção *Notify On*, selecione uma ou mais das seguintes caixas de seleção:
+
** Execução do fluxo de trabalho iniciada
** Execução do fluxo de trabalho concluída com êxito
** A execução do fluxo de trabalho falhou/foi parcialmente bem-sucedida
** Execução do fluxo de trabalho a aguardar aprovação
** Falha na aquisição


. Clique em *Enviar notificação de teste* para verificar as configurações.
. Clique em *Salvar*.

