---
permalink: help/task-configure-a-database-user-by-running-ocsetup-on-windows.html 
sidebar: sidebar 
keywords: configure, database, user, running, ocsetup, windows 
summary: Você pode executar o arquivo de configuração no servidor do Gerenciador Unificado do OnCommand para configurar o acesso somente leitura do banco de dados do OnCommand Unified Manager para o OnCommand Workflow Automation. 
---
= Configure um usuário de banco de dados executando o ocsetup no Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode executar o `ocsetup` arquivo no servidor do OnCommand Unified Manager para configurar o acesso somente leitura do banco de dados do OnCommand Unified Manager para o OnCommand Workflow Automation.

.Passos
. Faça o download do `wfa_ocsetup.exe` arquivo para um diretório no servidor do Gerenciador Unificado do OnCommand a partir do seguinte local:
+
_Https:_//WFA_Server_IP/download/wfa_ocsetup.exe.

+
`WFA_Server_IP` É o endereço IP (endereço IPv4 ou IPv6) do seu servidor WFA.

+
Se você tiver especificado uma porta não padrão para O WFA, você deve incluir o número da porta da seguinte forma:

+
_https:_//wfa_server_ip:port/download/wfa_ocsetup.exe.

+
`port` É o número da porta TCP que você usou para o servidor WFA durante a instalação.

+
Se você estiver especificando um endereço IPv6, você deve incluí-lo com colchetes.

. Clique duas vezes no `wfa_ocsetup.exe` ficheiro.
. Leia as informações no assistente de configuração e clique em *Next*.
. Navegue ou digite o local do JRE e clique em *Next*.
. Introduza um nome de utilizador e uma palavra-passe para substituir as credenciais predefinidas.
+
Uma nova conta de usuário de banco de dados é criada com acesso ao banco de dados do OnCommand Unified Manager.

+

NOTE: Se você não criar uma conta de usuário, as credenciais padrão serão usadas. Você deve criar uma conta de usuário para fins de segurança.

. Clique em *seguinte* e reveja os resultados.
. Clique em *Next* e, em seguida, clique em *Finish* para concluir o assistente.

